"""System Card Markdown Generator.

T178: Generate system_card.md output
§3.4: Digest Everything Pipeline
US4: Digest Everything Pipeline
"""

from pathlib import Path
from typing import , Any
from datetime import datetime
import logging

logger = logging.getLogger(__name__)


def generate_system_card(
    source_path: Path,
    parsed_data: dict[str, Any],
    analyzed_data: dict[str, Any],
    profile: dict[str, Any],
) -> str:
    """Generate system_card.md with human-readable documentation.

    Args:
        source_path: Path to source repository
        parsed_data: Parsed code structure
        analyzed_data: Analysis results
        profile: Profile data

    Returns:
        Markdown content
    """
    logger.info("Generating system_card.md")

    stats = profile.get("statistics", {})
    languages = stats.get("languages", {})

    md = f"""# System Card: {source_path.name}

**Generated**: {datetime.utcnow().isoformat()}
**Source**: {source_path}

## Overview

This system card provides a high-level overview of the codebase structure and characteristics.

## Statistics

- **Total Files**: {stats.get('total_files', 0)}
- **Total Functions**: {stats.get('total_functions', 0)}
- **Total Classes**: {stats.get('total_classes', 0)}

## Languages

"""
    for lang, count in languages.items():
        md += f"- **{lang.title()}**: {count} files\n"

    md += "\n## Structure\n\n"

    if parsed_data.get("functions"):
        md += "### Functions\n\n"
        for func in parsed_data["functions"][:20]:  # Top 20
            md += f"- `{func.get('name', 'unknown')}` (line {func.get('line', '?')})\n"
        md += "\n"

    if parsed_data.get("classes"):
        md += "### Classes\n\n"
        for cls in parsed_data["classes"][:20]:  # Top 20
            md += f"- `{cls.get('name', 'unknown')}` (line {cls.get('line', '?')})\n"
        md += "\n"

    md += "## Notes\n\n"
    md += "This system card was automatically generated by the NOA Digest Pipeline.\n"

    return md


def write_system_card(content: str, output_path: Path) -> None:
    """Write system_card.md to file.

    Args:
        content: Markdown content
        output_path: Output file path
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(content)
    logger.info(f"System card written to {output_path}")

