#!/bin/bash
#
# Abacus Desktop installer for NOA (Unix)
#
# Downloads and installs Abacus Desktop to noa_root/opt/abacus-desktop/.
# Creates wrapper script in noa_root/bin/ for easy access.
# Abacus Desktop is required for Abacus CLI authentication (AI provider).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NOA_ROOT="${NOA_ROOT:-$(dirname "$(dirname "$(dirname "$(dirname "$SCRIPT_DIR")")")")}"

OPT_DIR="$NOA_ROOT/opt"
BIN_DIR="$NOA_ROOT/bin"
INSTALL_DIR="$OPT_DIR/abacus-desktop"
WRAPPER_PATH="$BIN_DIR/abacus-desktop"
FORCE="${1:-}"

# Platform detection
if [[ "$OSTYPE" == "darwin"* ]]; then
    PLATFORM="macos"
    DOWNLOAD_URL="https://desktop.abacus.ai/download/macos/dmg/latest"
    INSTALLER_EXT="dmg"
else
    PLATFORM="linux"
    DOWNLOAD_URL="https://desktop.abacus.ai/download/linux/appimage/latest"
    INSTALLER_EXT="AppImage"
fi

INSTALLER_PATH="$OPT_DIR/AbacusAI-latest.$INSTALLER_EXT"

echo "NOA Abacus Desktop Installer"
echo "Platform: $PLATFORM"
echo "NOA_ROOT: $NOA_ROOT"
echo ""

# Create directories
mkdir -p "$OPT_DIR" "$BIN_DIR"

# Check if already installed
if [[ -d "$INSTALL_DIR" && "$FORCE" != "--force" ]]; then
    if [[ -x "$INSTALL_DIR/bin/abacus" ]] || [[ -x "$INSTALL_DIR/Abacus.app/Contents/MacOS/Abacus" ]]; then
        echo "  [OK] Abacus Desktop already installed"
        echo "  Location: $INSTALL_DIR"
        echo "  Use --force to reinstall"
        exit 0
    fi
fi

# Download installer
if [[ ! -f "$INSTALLER_PATH" ]]; then
    echo "  [INFO] Downloading Abacus Desktop..."
    echo "  URL: $DOWNLOAD_URL"

    if command -v curl &>/dev/null; then
        curl -L -o "$INSTALLER_PATH" "$DOWNLOAD_URL" || {
            echo "  [ERROR] Download failed"
            echo ""
            echo "  Manual installation:"
            echo "    1. Download from: https://desktop.abacus.ai/"
            echo "    2. Save to: $INSTALLER_PATH"
            echo "    3. Run this script again"
            exit 1
        }
    elif command -v wget &>/dev/null; then
        wget -O "$INSTALLER_PATH" "$DOWNLOAD_URL" || {
            echo "  [ERROR] Download failed"
            exit 1
        }
    else
        echo "  [ERROR] Neither curl nor wget available"
        exit 1
    fi

    echo "  [OK] Downloaded: $INSTALLER_PATH"
else
    echo "  [OK] Installer already downloaded"
fi

# Install based on platform
echo "  [INFO] Installing Abacus Desktop to NOA opt directory..."
echo "  Target: $INSTALL_DIR"

mkdir -p "$INSTALL_DIR"

case "$PLATFORM" in
    macos)
        # Mount DMG and copy app bundle
        if command -v hdiutil &>/dev/null; then
            MOUNT_POINT=$(hdiutil attach "$INSTALLER_PATH" | grep Volumes | awk '{print $3}')
            cp -R "$MOUNT_POINT"/*.app "$INSTALL_DIR/" 2>/dev/null || true
            hdiutil detach "$MOUNT_POINT"
            echo "  [OK] Installed Abacus.app to $INSTALL_DIR"
        else
            echo "  [ERROR] hdiutil not available (macOS only)"
            exit 1
        fi

        ABACUS_BIN="$INSTALL_DIR/Abacus.app/Contents/MacOS/Abacus"
        ;;

    linux)
        # Make AppImage executable and place in install dir
        chmod +x "$INSTALLER_PATH"
        cp "$INSTALLER_PATH" "$INSTALL_DIR/Abacus.AppImage"
        echo "  [OK] Installed AppImage to $INSTALL_DIR"

        ABACUS_BIN="$INSTALL_DIR/Abacus.AppImage"
        ;;
esac

# Verify installation
if [[ ! -e "$ABACUS_BIN" ]]; then
    echo "  [ERROR] Installation verification failed"
    echo "  Expected: $ABACUS_BIN"
    exit 1
fi

echo "  [OK] Found: $ABACUS_BIN"

# Create wrapper script
echo "  [INFO] Creating wrapper script..."

cat > "$WRAPPER_PATH" <<EOF
#!/bin/bash
# Abacus Desktop Wrapper - Generated by NOA bootstrap
# Launches Abacus Desktop from NOA opt directory
# Required for Abacus CLI authentication (AI provider)

"$ABACUS_BIN" "\$@"
EOF

chmod +x "$WRAPPER_PATH"
echo "  [OK] Created wrapper: $WRAPPER_PATH"

# Update provider config
PROVIDER_CONFIG="$NOA_ROOT/ai/providers/cloud/abacus/config.json"
if [[ -f "$PROVIDER_CONFIG" ]]; then
    echo "  [INFO] Updating provider configuration..."

    # Use jq if available, otherwise manual JSON update
    if command -v jq &>/dev/null; then
        jq --arg bin "$ABACUS_BIN" --arg wrapper "$WRAPPER_PATH" \
            '.desktop = {
                binaryPath: {
                    windows: "${NOA_ROOT}/opt/abacus-desktop/Abacus.exe",
                    unix: $bin
                },
                wrapper: {
                    windows: "${NOA_ROOT}/bin/abacus-desktop.cmd",
                    unix: $wrapper
                }
            }' "$PROVIDER_CONFIG" > "$PROVIDER_CONFIG.tmp"

        mv "$PROVIDER_CONFIG.tmp" "$PROVIDER_CONFIG"
        echo "  [OK] Updated provider config"
    else
        echo "  [WARN] jq not available, skipping config update"
    fi
fi

echo ""
echo "Abacus Desktop installation complete!"
echo ""
echo "Location: $INSTALL_DIR"
echo "Wrapper:  $WRAPPER_PATH"
echo ""
echo "Usage:"
echo "  abacus-desktop        # Launch Abacus Desktop"
echo ""
echo "Note: Abacus Desktop authentication is required for Abacus CLI"
echo "      Sign in to Abacus Desktop before using 'abacusai' CLI commands"
