<#
.SYNOPSIS
    Configure Cursor IDE for NOA integration.

.DESCRIPTION
    Detects Cursor installation and configures CLI integration.
    Creates wrapper script in NOA bin directory.

.PARAMETER NoaRoot
    NOA root directory (default: auto-detect)

.EXAMPLE
    .\cursor.ps1
#>
[CmdletBinding()]
param(
    [string]$NoaRoot
)

$ErrorActionPreference = "Stop"

# Auto-detect NOA_ROOT
if (-not $NoaRoot) {
    $NoaRoot = if ($env:NOA_ROOT) { $env:NOA_ROOT } else {
        Split-Path -Parent (Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $PSScriptRoot)))
    }
}

$BIN_DIR = Join-Path $NoaRoot "bin"
$WRAPPER_PATH = Join-Path $BIN_DIR "cursor.cmd"

Write-Host "Configuring Cursor IDE integration..." -ForegroundColor Cyan

# Common Cursor installation paths
$cursorPaths = @(
    "$env:LOCALAPPDATA\Programs\cursor\Cursor.exe"
    "C:\Program Files\Cursor\Cursor.exe"
    "$env:USERPROFILE\AppData\Local\Programs\cursor\Cursor.exe"
)

$cursorExe = $null
foreach ($path in $cursorPaths) {
    if (Test-Path $path) {
        $cursorExe = $path
        break
    }
}

if (-not $cursorExe) {
    Write-Host "  [SKIP] Cursor IDE not found in standard locations" -ForegroundColor Yellow
    Write-Host "  Install from: https://cursor.sh/" -ForegroundColor Gray
    exit 0
}

Write-Host "  Found: $cursorExe" -ForegroundColor Green

# Ensure bin directory exists
if (-not (Test-Path $BIN_DIR)) {
    New-Item -ItemType Directory -Path $BIN_DIR -Force | Out-Null
}

# Check if wrapper already exists
if (Test-Path $WRAPPER_PATH) {
    Write-Host "  [EXISTS] Cursor wrapper already configured" -ForegroundColor Gray
    return
}

# Create CLI wrapper
$wrapperContent = @"
@echo off
REM Cursor CLI Wrapper - Generated by NOA bootstrap
REM Launches Cursor with CLI arguments

"$cursorExe" %*
"@

$wrapperContent | Set-Content -Path $WRAPPER_PATH -Encoding ASCII
Write-Host "  [OK] Created Cursor wrapper: $WRAPPER_PATH" -ForegroundColor Green

# Verify wrapper works
try {
    $version = & $WRAPPER_PATH --version 2>&1 | Select-Object -First 1
    Write-Host "  [OK] Verified: $version" -ForegroundColor Green
} catch {
    Write-Host "  [WARN] Wrapper created but version check failed" -ForegroundColor Yellow
}

