#!/bin/bash
#
# configsure Cursor IDE for NOA integration.
#
# Detects Cursor installation and configsures CLI integration.
# Creates wrapper script in NOA bin directory.
#
# Usage:
#   ./cursor.sh

set -euo pipefail

# Auto-detect NOA_ROOT
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NOA_ROOT="${NOA_ROOT:-$(cd "$SCRIPT_DIR/../../../.." && pwd)}"
BIN_DIR="$NOA_ROOT/bin"
WRAPPER_PATH="$BIN_DIR/cursor"

echo -e "\033[36mconfigsuring Cursor IDE integration...\033[0m"

# Detect OS
OS="$(uname -s)"

# Common Cursor installation paths by OS
CURSOR_EXE=""
case "$OS" in
    Darwin)
        # macOS
        CURSOR_PATHS=(
            "/Applications/Cursor.app/Contents/MacOS/Cursor"
            "$HOME/Applications/Cursor.app/Contents/MacOS/Cursor"
        )
        ;;
    Linux)
        # Linux
        CURSOR_PATHS=(
            "/usr/bin/cursor"
            "/usr/local/bin/cursor"
            "$HOME/.local/bin/cursor"
            "/opt/cursor/cursor"
            "/snap/bin/cursor"
        )
        ;;
    *)
        echo -e "  \033[33m[SKIP]\033[0m Unsupported OS: $OS"
        exit 0
        ;;
esac

for path in "${CURSOR_PATHS[@]}"; do
    if [[ -x "$path" ]]; then
        CURSOR_EXE="$path"
        break
    fi
done

if [[ -z "$CURSOR_EXE" ]]; then
    echo -e "  \033[33m[SKIP]\033[0m Cursor IDE not found in standard locations"
    echo -e "  \033[90mInstall from: https://cursor.sh/\033[0m"
    exit 0
fi

echo -e "  \033[32mFound:\033[0m $CURSOR_EXE"

# Ensure bin directory exists
mkdir -p "$BIN_DIR"

# Check if wrapper already exists
if [[ -f "$WRAPPER_PATH" ]]; then
    echo -e "  \033[90m[EXISTS]\033[0m Cursor wrapper already configsured"
    exit 0
fi

# Create CLI wrapper
cat > "$WRAPPER_PATH" << EOF
#!/bin/bash
# Cursor CLI Wrapper - Generated by NOA bootstrap
# Launches Cursor with CLI arguments

exec "$CURSOR_EXE" "\$@"
EOF

chmod +x "$WRAPPER_PATH"
echo -e "  \033[32m[OK]\033[0m Created Cursor wrapper: $WRAPPER_PATH"

# Verify wrapper works
if VERSION=$("$WRAPPER_PATH" --version 2>&1 | head -1); then
    echo -e "  \033[32m[OK]\033[0m Verified: $VERSION"
else
    echo -e "  \033[33m[WARN]\033[0m Wrapper created but version check failed"
fi

