<#
.SYNOPSIS
    configsure VS Code for NOA integration.

.DESCRIPTION
    Detects VS Code installation and creates CLI wrapper in NOA bin.

.PARAMETER NoaRoot
    NOA root directory (default: auto-detect)

.EXAMPLE
    .\vscode.ps1
#>
[CmdletBinding()]
param(
    [string]$NoaRoot
)

$ErrorActionPreference = "Stop"

# Auto-detect NOA_ROOT
if (-not $NoaRoot) {
    $NoaRoot = if ($env:NOA_ROOT) { $env:NOA_ROOT } else {
        Split-Path -Parent (Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $PSScriptRoot)))
    }
}

$BIN_DIR = Join-Path $NoaRoot "bin"
$WRAPPER_PATH = Join-Path $BIN_DIR "code.cmd"

Write-Host "configsuring VS Code integration..." -ForegroundColor Cyan

# Check if code command is already available
$codeCmd = Get-Command code -ErrorAction SilentlyContinue
if ($codeCmd) {
    Write-Host "  Found: $($codeCmd.Source)" -ForegroundColor Green

    # Create wrapper pointing to existing code command
    if (-not (Test-Path $BIN_DIR)) {
        New-Item -ItemType Directory -Path $BIN_DIR -Force | Out-Null
    }

    if (Test-Path $WRAPPER_PATH) {
        Write-Host "  [EXISTS] VS Code wrapper already configsured" -ForegroundColor Gray
        return
    }

    $wrapperContent = @"
@echo off
REM VS Code CLI Wrapper - Generated by NOA bootstrap
"$($codeCmd.Source)" %*
"@

    $wrapperContent | Set-Content -Path $WRAPPER_PATH -Encoding ASCII
    Write-Host "  [OK] Created VS Code wrapper: $WRAPPER_PATH" -ForegroundColor Green
    return
}

# Try to find VS Code manually
$vscodePaths = @(
    "$env:LOCALAPPDATA\Programs\Microsoft VS Code\Code.exe"
    "C:\Program Files\Microsoft VS Code\Code.exe"
    "$env:ProgramFiles\Microsoft VS Code\Code.exe"
)

$vscodeExe = $null
foreach ($path in $vscodePaths) {
    if (Test-Path $path) {
        $vscodeExe = $path
        break
    }
}

if (-not $vscodeExe) {
    Write-Host "  [SKIP] VS Code not found in standard locations" -ForegroundColor Yellow
    Write-Host "  Install from: https://code.visualstudio.com/" -ForegroundColor Gray
    exit 0
}

Write-Host "  Found: $vscodeExe" -ForegroundColor Green

# Ensure bin directory exists
if (-not (Test-Path $BIN_DIR)) {
    New-Item -ItemType Directory -Path $BIN_DIR -Force | Out-Null
}

# Create CLI wrapper
$wrapperContent = @"
@echo off
REM VS Code CLI Wrapper - Generated by NOA bootstrap
"$vscodeExe" %*
"@

$wrapperContent | Set-Content -Path $WRAPPER_PATH -Encoding ASCII
Write-Host "  [OK] Created VS Code wrapper: $WRAPPER_PATH" -ForegroundColor Green

