#!/bin/bash
#
# configsure VS Code for NOA integration.
#
# Detects VS Code installation and creates CLI wrapper in NOA bin.
#
# Usage:
#   ./vscode.sh

set -euo pipefail

# Auto-detect NOA_ROOT
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NOA_ROOT="${NOA_ROOT:-$(cd "$SCRIPT_DIR/../../../.." && pwd)}"
BIN_DIR="$NOA_ROOT/bin"
WRAPPER_PATH="$BIN_DIR/code"

echo -e "\033[36mconfigsuring VS Code integration...\033[0m"

# Check if code command is already available
if command -v code &> /dev/null; then
    CODE_PATH="$(command -v code)"
    echo -e "  \033[32mFound:\033[0m $CODE_PATH"

    mkdir -p "$BIN_DIR"

    if [[ -f "$WRAPPER_PATH" ]]; then
        echo -e "  \033[90m[EXISTS]\033[0m VS Code wrapper already configsured"
        exit 0
    fi

    # Create symlink or wrapper
    if [[ -L "$CODE_PATH" ]] || [[ -x "$CODE_PATH" ]]; then
        ln -sf "$CODE_PATH" "$WRAPPER_PATH" 2>/dev/null || \
        cat > "$WRAPPER_PATH" << EOF
#!/bin/bash
exec "$CODE_PATH" "\$@"
EOF
        chmod +x "$WRAPPER_PATH"
    fi

    echo -e "  \033[32m[OK]\033[0m Created VS Code wrapper: $WRAPPER_PATH"
    exit 0
fi

# Try to find VS Code manually by OS
OS="$(uname -s)"
VSCODE_EXE=""

case "$OS" in
    Darwin)
        VSCODE_PATHS=(
            "/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code"
            "$HOME/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code"
        )
        ;;
    Linux)
        VSCODE_PATHS=(
            "/usr/bin/code"
            "/usr/local/bin/code"
            "/snap/bin/code"
            "/usr/share/code/bin/code"
        )
        ;;
    *)
        echo -e "  \033[33m[SKIP]\033[0m Unsupported OS: $OS"
        exit 0
        ;;
esac

for path in "${VSCODE_PATHS[@]}"; do
    if [[ -x "$path" ]]; then
        VSCODE_EXE="$path"
        break
    fi
done

if [[ -z "$VSCODE_EXE" ]]; then
    echo -e "  \033[33m[SKIP]\033[0m VS Code not found in standard locations"
    echo -e "  \033[90mInstall from: https://code.visualstudio.com/\033[0m"
    exit 0
fi

echo -e "  \033[32mFound:\033[0m $VSCODE_EXE"

# Ensure bin directory exists
mkdir -p "$BIN_DIR"

# Create CLI wrapper
cat > "$WRAPPER_PATH" << EOF
#!/bin/bash
# VS Code CLI Wrapper - Generated by NOA bootstrap
exec "$VSCODE_EXE" "\$@"
EOF

chmod +x "$WRAPPER_PATH"
echo -e "  \033[32m[OK]\033[0m Created VS Code wrapper: $WRAPPER_PATH"

