#!/bin/bash
#
# Configure AI provider caches (Ollama, HuggingFace, llama.cpp).
#
# Sets up cache directories and environment variables for AI model providers.
#
# Usage:
#   ./provider-cache.sh

set -euo pipefail

# Auto-detect NOA_ROOT
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NOA_ROOT="${NOA_ROOT:-$(cd "$SCRIPT_DIR/../../.." && pwd)}"
CACHE_DIR="$NOA_ROOT/cache"

echo -e "\033[36mConfiguring AI provider caches...\033[0m"
echo -e "\033[90mNOA Root: $NOA_ROOT\033[0m"
echo ""

# Provider-specific cache configurations
declare -A PROVIDERS=(
    ["ollama"]="OLLAMA_MODELS:$CACHE_DIR/ollama:Ollama model storage"
    ["huggingface"]="HF_HOME:$CACHE_DIR/huggingface:HuggingFace Hub cache"
    ["llama-cpp"]="LLAMA_CACHE:$CACHE_DIR/models:llama.cpp model cache"
    ["transformers"]="TRANSFORMERS_CACHE:$CACHE_DIR/huggingface/hub:Transformers model cache"
)

for provider in "${!PROVIDERS[@]}"; do
    IFS=':' read -r env_var path description <<< "${PROVIDERS[$provider]}"

    if [[ ! -d "$path" ]]; then
        mkdir -p "$path"
        echo -e "  \033[32m[CREATE]\033[0m $provider: $path"
    else
        echo -e "  \033[90m[EXISTS]\033[0m $provider: $path"
    fi
done

echo ""
echo -e "\033[32mProvider cache configuration complete.\033[0m"
echo ""
echo -e "\033[33mAdd to your shell profile:\033[0m"

for provider in "${!PROVIDERS[@]}"; do
    IFS=':' read -r env_var path description <<< "${PROVIDERS[$provider]}"
    echo -e "  \033[36mexport $env_var=\"$path\"\033[0m"
done

# Generate env config snippet
ENV_CONFIG_PATH="$CACHE_DIR/provider-cache-env.sh"
cat > "$ENV_CONFIG_PATH" << EOF
# AI Provider Cache Environment Variables
# Generated by provider-cache.sh

EOF

for provider in "${!PROVIDERS[@]}"; do
    IFS=':' read -r env_var path description <<< "${PROVIDERS[$provider]}"
    echo "export $env_var=\"$path\"" >> "$ENV_CONFIG_PATH"
done

echo ""
echo -e "\033[32mEnvironment config saved to: $ENV_CONFIG_PATH\033[0m"

