<#
.SYNOPSIS
    configsure AI provider caches (Ollama, HuggingFace, llama.cpp).

.DESCRIPTION
    Sets up cache directories and environment variables for AI model providers.

.PARAMETER NoaRoot
    NOA root directory (default: auto-detect)

.EXAMPLE
    .\provider-cache.ps1
#>
[CmdletBinding()]
param(
    [string]$NoaRoot
)

$ErrorActionPreference = "Stop"

# Auto-detect NOA_ROOT
if (-not $NoaRoot) {
    $NoaRoot = if ($env:NOA_ROOT) { $env:NOA_ROOT } else {
        Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $PSScriptRoot))
    }
}

$CACHE_DIR = Join-Path $NoaRoot "cache"

Write-Host "configsuring AI provider caches..." -ForegroundColor Cyan
Write-Host "NOA Root: $NoaRoot" -ForegroundColor Gray
Write-Host ""

# Provider-specific cache configsurations
$providerCaches = @(
    @{
        Name = "ollama"
        EnvVar = "OLLAMA_MODELS"
        Path = Join-Path $CACHE_DIR "ollama"
        Description = "Ollama model storage"
    },
    @{
        Name = "huggingface"
        EnvVar = "HF_HOME"
        Path = Join-Path $CACHE_DIR "huggingface"
        Description = "HuggingFace Hub cache"
    },
    @{
        Name = "llama-cpp"
        EnvVar = "LLAMA_CACHE"
        Path = Join-Path $CACHE_DIR "models"
        Description = "llama.cpp model cache"
    },
    @{
        Name = "transformers"
        EnvVar = "TRANSFORMERS_CACHE"
        Path = Join-Path $CACHE_DIR "huggingface/hub"
        Description = "Transformers model cache"
    }
)

foreach ($provider in $providerCaches) {
    # Create cache directory
    if (-not (Test-Path $provider.Path)) {
        New-Item -ItemType Directory -Path $provider.Path -Force | Out-Null
        Write-Host "  [CREATE] $($provider.Name): $($provider.Path)" -ForegroundColor Green
    } else {
        Write-Host "  [EXISTS] $($provider.Name): $($provider.Path)" -ForegroundColor Gray
    }
}

Write-Host ""
Write-Host "Provider cache configsuration complete." -ForegroundColor Green
Write-Host ""
Write-Host "Add to your environment profile:" -ForegroundColor Yellow

foreach ($provider in $providerCaches) {
    Write-Host "  `$env:$($provider.EnvVar) = `"$($provider.Path)`"" -ForegroundColor Cyan
}

# Generate env configs snippet
$envconfigsPath = Join-Path $CACHE_DIR "provider-cache-env.ps1"
$envContent = @"
# AI Provider Cache Environment Variables
# Generated by provider-cache.ps1

"@

foreach ($provider in $providerCaches) {
    $envContent += "`$env:$($provider.EnvVar) = `"$($provider.Path)`"`n"
}

$envContent | Set-Content -Path $envconfigsPath -Encoding UTF8
Write-Host ""
Write-Host "Environment configs saved to: $envconfigsPath" -ForegroundColor Green

