<#
.SYNOPSIS
    Install Cursor CLI to noa_root/opt/

.DESCRIPTION
    Downloads or configures Cursor CLI for headless operation.
    Cursor is typically installed as an IDE; this configures the CLI component.

    Provider Config: ai/providers/hybrid/cursor/config.json

.PARAMETER NoaRoot
    Root directory for NOA installation. Defaults to N:\noa

.PARAMETER Method
    Installation method: detect (default), manual
    - detect: Look for existing Cursor installation and configure CLI
    - manual: Provide manual download instructions

.EXAMPLE
    .\cursor-cli.ps1
    Detect existing Cursor installation
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory=$false)]
    [string]$NoaRoot = "N:\noa",

    [Parameter(Mandatory=$false)]
    [ValidateSet("detect", "manual")]
    [string]$Method = "detect"
)

$ErrorActionPreference = "Stop"

function Write-Log {
    param([string]$Message, [string]$Level = "Info")
    $color = switch ($Level) {
        "Success" { "Green" }
        "Warning" { "Yellow" }
        "Error" { "Red" }
        default { "White" }
    }
    Write-Host "[$Level] $Message" -ForegroundColor $color
}

# Configuration
$ProviderConfigPath = Join-Path $NoaRoot "ai/providers/hybrid/cursor"

Write-Log "Setting up Cursor CLI..." -Level Info
Write-Log "  Method: $Method" -Level Info
Write-Log "  NOA Root: $NoaRoot" -Level Info

# Ensure directories exist
$optPath = Join-Path $NoaRoot "opt"
$binPath = Join-Path $NoaRoot "bin"
$cursorOptPath = Join-Path $optPath "cursor-cli"

foreach ($dir in @($optPath, $binPath, $ProviderConfigPath, $cursorOptPath)) {
    if (-not (Test-Path $dir)) {
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
        Write-Log "  Created: $dir" -Level Success
    }
}

switch ($Method) {
    "detect" {
        Write-Log "Detecting existing Cursor installation..." -Level Info

        # Common Cursor installation locations on Windows
        $cursorLocations = @(
            "$env:LOCALAPPDATA\Programs\Cursor\Cursor.exe",
            "$env:LOCALAPPDATA\cursor\Cursor.exe",
            "C:\Program Files\Cursor\Cursor.exe",
            "C:\Program Files (x86)\Cursor\Cursor.exe"
        )

        $cursorPath = $null
        foreach ($loc in $cursorLocations) {
            if (Test-Path $loc) {
                $cursorPath = $loc
                break
            }
        }

        if ($cursorPath) {
            Write-Log "  Found Cursor at: $cursorPath" -Level Success

            # Create a wrapper script for CLI usage
            $wrapperScript = @"
@echo off
REM Cursor CLI Wrapper - Generated by NOA bootstrap
REM Launches Cursor with CLI arguments

"$cursorPath" %*
"@
            $wrapperPath = Join-Path $binPath "cursor.cmd"
            Set-Content -Path $wrapperPath -Value $wrapperScript -Encoding ASCII
            Write-Log "  Created wrapper: $wrapperPath" -Level Success
        } else {
            Write-Log "  Cursor not found in common locations" -Level Warning
            Write-Log "  Please install Cursor from https://cursor.com" -Level Info
        }
    }

    "manual" {
        Write-Log "Manual Cursor setup instructions:" -Level Info
        Write-Host ""
        Write-Host "1. Download Cursor from: https://cursor.com" -ForegroundColor Cyan
        Write-Host "2. Install to default location" -ForegroundColor Cyan
        Write-Host "3. Re-run this script with -Method detect" -ForegroundColor Cyan
        Write-Host ""
        Write-Host "For headless CLI usage, see:" -ForegroundColor Gray
        Write-Host "  https://cursor.com/docs/cli/headless" -ForegroundColor Gray
    }
}

# Create provider config if not exists
$configFile = Join-Path $ProviderConfigPath "config.json"
if (-not (Test-Path $configFile)) {
    Write-Log "Provider config already exists at ai/providers/hybrid/cursor/" -Level Info
}

Write-Log "Cursor CLI setup complete!" -Level Success
Write-Log "  Provider config: $ProviderConfigPath" -Level Info
Write-Log "  Shared resources: $NoaRoot\ai\shared" -Level Info

exit 0


