-- NOA PostgreSQL Core Schema (RuVector-first)
-- Migration: pg/001_core
-- Date: 2025-12-22
--
-- Server deployments use PostgreSQL + RuVector.
-- This migration intentionally avoids requiring uuid generation extensions.
-- IDs are UUID-typed but must be generated by the application.

-- Required for vector columns + ANN indexes.
CREATE EXTENSION IF NOT EXISTS ruvector;

-- Optional but commonly useful.
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- ============================================================================
-- Core tables
-- ============================================================================

CREATE TABLE IF NOT EXISTS model (
    id UUID PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    name TEXT NOT NULL,
    provider TEXT,
    kind TEXT,
    metadata JSONB
);

CREATE TABLE IF NOT EXISTS device (
    id UUID PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    name TEXT NOT NULL,
    platform TEXT,
    metadata JSONB
);

CREATE TABLE IF NOT EXISTS agent (
    id UUID PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    name TEXT NOT NULL,
    metadata JSONB
);

CREATE TABLE IF NOT EXISTS agent_log (
    id UUID PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    agent_id UUID REFERENCES agent(id) ON DELETE SET NULL,
    level TEXT NOT NULL,
    message TEXT NOT NULL,
    fields JSONB
);

CREATE INDEX IF NOT EXISTS idx_agent_log_created_at ON agent_log (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_log_agent_id ON agent_log (agent_id);

CREATE TABLE IF NOT EXISTS digest_source (
    id UUID PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    uri TEXT NOT NULL,
    source_type TEXT NOT NULL,
    metadata JSONB,
    checksum TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_digest_source_uri ON digest_source (uri);

-- ============================================================================
-- Knowledge graph
-- ============================================================================

CREATE TABLE IF NOT EXISTS knowledge_node (
    id UUID PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    node_type TEXT NOT NULL,
    name TEXT NOT NULL,
    qualified_name TEXT,
    description TEXT,
    location JSONB,
    properties JSONB,
    source_digest UUID REFERENCES digest_source(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_knowledge_node_type ON knowledge_node (node_type);
CREATE INDEX IF NOT EXISTS idx_knowledge_node_qualified_name ON knowledge_node (qualified_name);

CREATE TABLE IF NOT EXISTS knowledge_edge (
    id UUID PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    edge_type TEXT NOT NULL,
    from_id UUID NOT NULL REFERENCES knowledge_node(id) ON DELETE CASCADE,
    to_id UUID NOT NULL REFERENCES knowledge_node(id) ON DELETE CASCADE,
    properties JSONB
);

CREATE INDEX IF NOT EXISTS idx_knowledge_edge_from ON knowledge_edge (from_id);
CREATE INDEX IF NOT EXISTS idx_knowledge_edge_to ON knowledge_edge (to_id);

-- ============================================================================
-- Memory
-- ============================================================================

CREATE TABLE IF NOT EXISTS memory (
    id UUID PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    memory_type TEXT NOT NULL,
    content TEXT NOT NULL,
    metadata JSONB,
    source_agent UUID REFERENCES agent(id) ON DELETE SET NULL,
    parent_id UUID REFERENCES memory(id) ON DELETE SET NULL,
    tags TEXT[],
    checksum TEXT
);

CREATE INDEX IF NOT EXISTS idx_memory_created_at ON memory (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_memory_type ON memory (memory_type);
CREATE INDEX IF NOT EXISTS idx_memory_tags ON memory USING GIN (tags);

-- ============================================================================
-- Embeddings (vector storage)
-- ============================================================================

CREATE TABLE IF NOT EXISTS embedding (
    id UUID PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    -- Vector type provided by RuVector extension
    vector ruvector(384) NOT NULL,
    model_id UUID REFERENCES model(id) ON DELETE SET NULL,
    source_type TEXT NOT NULL CHECK (source_type IN ('memory', 'knowledge_node', 'digest_source')),
    source_id UUID NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_embedding_source ON embedding (source_type, source_id);

ALTER TABLE memory
    ADD COLUMN IF NOT EXISTS embedding_id UUID REFERENCES embedding(id) ON DELETE SET NULL;

ALTER TABLE knowledge_node
    ADD COLUMN IF NOT EXISTS embedding_id UUID REFERENCES embedding(id) ON DELETE SET NULL;

-- ============================================================================
-- Tasks
-- ============================================================================

CREATE TABLE IF NOT EXISTS task (
    id UUID PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    title TEXT NOT NULL,
    description TEXT,
    status TEXT NOT NULL,
    priority INTEGER,
    metadata JSONB
);

CREATE INDEX IF NOT EXISTS idx_task_status ON task (status);
CREATE INDEX IF NOT EXISTS idx_task_updated_at ON task (updated_at DESC);

CREATE TABLE IF NOT EXISTS task_event (
    id UUID PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    task_id UUID NOT NULL REFERENCES task(id) ON DELETE CASCADE,
    event_type TEXT NOT NULL,
    payload JSONB
);

CREATE INDEX IF NOT EXISTS idx_task_event_task_id ON task_event (task_id);
CREATE INDEX IF NOT EXISTS idx_task_event_created_at ON task_event (created_at DESC);

-- ============================================================================
-- Sync
-- ============================================================================

CREATE TABLE IF NOT EXISTS sync_state (
    id UUID PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    peer_id TEXT,
    last_sync_at TIMESTAMPTZ,
    state JSONB
);
