version: "2"
services:
  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  # Collector
  otel-collector:
    image: otel/opentelemetry-collector:0.88.0
    restart: always
    command: ["--configs=/etc/otel-collector-configs.yaml"]
    volumes:
      - ./otel-collector-configs.yaml:/etc/otel-collector-configs.yaml
    ports:
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
    depends_on:
      - jaeger-all-in-one
