<#
.SYNOPSIS
    Install GitHub Desktop into NOA portable apps directory.

.DESCRIPTION
    Places GitHub Desktop under $NOA_ROOT/opt/apps/github-desktop/ with data redirected
    to $NOA_ROOT/data/apps/github-desktop via NDCL wrapper.

.PARAMETER NoaRoot
    NOA root directory (auto-detected).

.PARAMETER Force
    Reinstall even if an existing binary is present.

.PARAMETER DownloadUrl
    Optional download URL. If omitted, the script expects an installer at opt/apps/github-desktop/GitHubDesktopSetup.exe.
#>
[CmdletBinding()]
param(
    [string]$NoaRoot,
    [switch]$Force,
    [string]$DownloadUrl
)

$ErrorActionPreference = "Stop"

if (-not $NoaRoot) {
    $NoaRoot = if ($env:NOA_ROOT) { $env:NOA_ROOT } else { Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $PSScriptRoot)) }
}

$optDir = Join-Path $NoaRoot "opt"
$installDir = Join-Path $optDir "apps\\github-desktop"
$binDir = Join-Path $NoaRoot "bin"
$installerPath = Join-Path $installDir "GitHubDesktopSetup.exe"
$exePath = Join-Path $installDir "GitHubDesktop.exe"
$wrapperPath = Join-Path $binDir "github-desktop.cmd"

Write-Host "[NDCL] GitHub Desktop installer" -ForegroundColor Cyan
Write-Host "NOA_ROOT: $NoaRoot" -ForegroundColor Gray
Write-Host ""

New-Item -ItemType Directory -Path $optDir -Force | Out-Null
New-Item -ItemType Directory -Path $installDir -Force | Out-Null
New-Item -ItemType Directory -Path (Join-Path $NoaRoot "data\\apps\\github-desktop") -Force | Out-Null
New-Item -ItemType Directory -Path $binDir -Force | Out-Null

if ((Test-Path $exePath) -and -not $Force) {
    Write-Host "  [OK] GitHub Desktop already present at $exePath" -ForegroundColor Green
    exit 0
}

if (-not (Test-Path $installerPath)) {
    if ($DownloadUrl) {
        Write-Host "  [INFO] Downloading installer..." -ForegroundColor Yellow
        try {
            Invoke-WebRequest -Uri $DownloadUrl -OutFile $installerPath
            Write-Host "  [OK] Downloaded installer to $installerPath" -ForegroundColor Green
        } catch {
            Write-Host "  [ERROR] Download failed: $_" -ForegroundColor Red
            Write-Host "         Place the installer at: $installerPath and rerun." -ForegroundColor Gray
            exit 1
        }
    } else {
        Write-Host "  [WARN] Installer not found at $installerPath" -ForegroundColor Yellow
        Write-Host "        Provide -DownloadUrl or place the installer manually, then rerun." -ForegroundColor Gray
        exit 1
    }
}

Write-Host "  [INFO] Running installer into NOA opt/apps..." -ForegroundColor Yellow
try {
    $args = @("/silent", "/verysilent", "/D=$installDir")
    $proc = Start-Process -FilePath $installerPath -ArgumentList $args -Wait -PassThru -NoNewWindow
    if ($proc.ExitCode -ne 0) {
        Write-Host "  [WARN] Installer exited with code $($proc.ExitCode)" -ForegroundColor Yellow
    } else {
        Write-Host "  [OK] Installation completed" -ForegroundColor Green
    }
} catch {
    Write-Host "  [ERROR] Installation failed: $_" -ForegroundColor Red
    exit 1
}

if (-not (Test-Path $exePath)) {
    Write-Host "  [WARN] GitHubDesktop.exe not found after install. Check installer output." -ForegroundColor Yellow
}

if (-not (Test-Path $wrapperPath)) {
    Write-Host "  [INFO] Creating launcher wrapper..." -ForegroundColor Yellow
    $wrapper = @"
@echo off
REM Generated by github-desktop.ps1
setlocal
set "NOA_ROOT=%NoaRoot%"
set "NOA_DATA=%NoaRoot%\data"
set "APPDATA=%NOA_DATA%\apps\github-desktop"
set "LOCALAPPDATA=%NOA_DATA%\apps\github-desktop"
"%exePath%" %*
"@
    $wrapper | Set-Content -Path $wrapperPath -Encoding ASCII
    Write-Host "  [OK] Wrapper created at $wrapperPath" -ForegroundColor Green
} else {
    Write-Host "  [OK] Wrapper already present at $wrapperPath" -ForegroundColor Green
}

Write-Host "  [DONE] GitHub Desktop prepared for NDCL containment" -ForegroundColor Cyan
