<#
.SYNOPSIS
    Install NOA environment into PowerShell profile
    
.DESCRIPTION
    Adds NOA environment loading to your PowerShell profile so it's available
    in every new terminal session.
    
.PARAMETER Uninstall
    Remove NOA from PowerShell profile
    
.EXAMPLE
    .\install-profile.ps1
    .\install-profile.ps1 -Uninstall
#>

param(
    [switch]$Uninstall
)

$NOA_ROOT = Split-Path -Parent $PSScriptRoot
$noaEnvPath = Join-Path $NOA_ROOT "noa-env.ps1"
$profilePath = $PROFILE.CurrentUserAllHosts

$markerStart = "# >>> NOA Environment >>>"
$markerEnd = "# <<< NOA Environment <<<"
$noaBlock = @"
$markerStart
# Auto-generated by NOA install-profile.ps1
# To remove, run: .\scripts\install-profile.ps1 -Uninstall
if (Test-Path "$noaEnvPath") {
    . "$noaEnvPath"
}
$markerEnd
"@

# Ensure profile directory exists
$profileDir = Split-Path -Parent $profilePath
if (-not (Test-Path $profileDir)) {
    New-Item -ItemType Directory -Path $profileDir -Force | Out-Null
}

# Read existing profile or create empty
if (Test-Path $profilePath) {
    $profileContent = Get-Content $profilePath -Raw
} else {
    $profileContent = ""
}

if ($Uninstall) {
    # Remove NOA block from profile
    if ($profileContent -match [regex]::Escape($markerStart)) {
        $pattern = [regex]::Escape($markerStart) + "[\s\S]*?" + [regex]::Escape($markerEnd) + "\r?\n?"
        $profileContent = $profileContent -replace $pattern, ""
        $profileContent = $profileContent.Trim()
        Set-Content -Path $profilePath -Value $profileContent -Encoding UTF8
        Write-Host "NOA removed from PowerShell profile: $profilePath" -ForegroundColor Green
    } else {
        Write-Host "NOA not found in PowerShell profile" -ForegroundColor Yellow
    }
} else {
    # Add NOA block to profile
    if ($profileContent -match [regex]::Escape($markerStart)) {
        Write-Host "NOA already installed in PowerShell profile" -ForegroundColor Yellow
        Write-Host "Run with -Uninstall to remove, then re-run to update" -ForegroundColor Gray
    } else {
        if ($profileContent) {
            $profileContent = $profileContent.TrimEnd() + "`n`n" + $noaBlock
        } else {
            $profileContent = $noaBlock
        }
        Set-Content -Path $profilePath -Value $profileContent -Encoding UTF8
        Write-Host "NOA installed to PowerShell profile: $profilePath" -ForegroundColor Green
        Write-Host ""
        Write-Host "Restart PowerShell or run:" -ForegroundColor Cyan
        Write-Host "  . `$PROFILE" -ForegroundColor White
    }
}
