#!/bin/bash
#
# Generate .noa-env shell script.
#
# Creates a shell script that sets up all NOA environment variables
# based on the current installation.
#
# Usage:
#   ./noa-env.sh
#   ./noa-env.sh --output /path/to/output

set -euo pipefail

# Auto-detect NOA_ROOT
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NOA_ROOT="${NOA_ROOT:-$(cd "$SCRIPT_DIR/../../.." && pwd)}"

OUTPUT_PATH="${1:-$NOA_ROOT/.noa-env}"

echo -e "\033[36mGenerating NOA environment script...\033[0m"

cat > "$OUTPUT_PATH" << EOF
# NOA Environment configsuration
# Generated by scripts/bootstrap/generators/noa-env.sh
# Date: $(date -Iseconds)

# Core paths
export NOA_ROOT="$NOA_ROOT"
export NOA_BIN="\$NOA_ROOT/bin"
export NOA_configs="\$NOA_ROOT/configs"
export NOA_SCRIPTS="\$NOA_ROOT/scripts"
export NOA_LOGS="\$NOA_ROOT/logs"
export NOA_CACHE="\$NOA_ROOT/cache"

# Optional packages
export NOA_OPT="\$NOA_ROOT/opt"
export NOA_REPOS="\$NOA_ROOT/repos"
export NOA_AI="\$NOA_ROOT/ai"

# Kernel-related (NKAL)
export NOA_SYS="\$NOA_ROOT/sys"
export NOA_NAMESPACE="\$NOA_SYS/namespace"
export NOA_CGROUP="\$NOA_SYS/cgroup"
export NOA_KERNEL="\$NOA_SYS/kernel"

# Go environment
export GOROOT="\$NOA_OPT/go"
export GOPATH="\$NOA_OPT/go/workspace"
export GOBIN="\$NOA_OPT/go/workspace/bin"
export GOCACHE="\$NOA_CACHE/go"
export GOMODCACHE="\$NOA_OPT/go/pkg/mod"

# Rust environment
export CARGO_HOME="\$NOA_OPT/rust/cargo"
export RUSTUP_HOME="\$NOA_OPT/rust/rustup"

# Python environment
export PIP_CACHE_DIR="\$NOA_CACHE/pip"

# Node.js environment
export npm_configs_cache="\$NOA_CACHE/npm"

# AI provider caches
export OLLAMA_MODELS="\$NOA_CACHE/ollama"
export HF_HOME="\$NOA_CACHE/huggingface"
export LLAMA_CACHE="\$NOA_CACHE/models"

# Add NOA directories to PATH
add_noa_path() {
    if [[ -d "\$1" ]] && [[ ":\$PATH:" != *":\$1:"* ]]; then
        export PATH="\$1:\$PATH"
    fi
}

add_noa_path "\$NOA_BIN"
add_noa_path "\$NOA_SCRIPTS"
add_noa_path "\$GOROOT/bin"
add_noa_path "\$GOBIN"
add_noa_path "\$CARGO_HOME/bin"

# Navigation aliases
alias cda='cd "\$NOA_ROOT"'
alias cdr='cd "\$NOA_REPOS"'
alias cds='cd "\$NOA_SCRIPTS"'
alias cdc='cd "\$NOA_configs"'
alias cdai='cd "\$NOA_AI"'

echo "NOA environment loaded: \$NOA_ROOT"
EOF

chmod +x "$OUTPUT_PATH"
echo -e "\033[32mGenerated: $OUTPUT_PATH\033[0m"

