<#
.SYNOPSIS
    Generate noa-env.ps1 environment script.

.DESCRIPTION
    Creates a PowerShell script that sets up all NOA environment variables
    based on the current installation.

.PARAMETER NoaRoot
    NOA root directory (default: auto-detect)

.PARAMETER OutputPath
    Path to save the generated script (default: noa-env.ps1 in repo root)

.EXAMPLE
    .\noa-env.ps1
#>
[CmdletBinding()]
param(
    [string]$NoaRoot,
    [string]$OutputPath
)

$ErrorActionPreference = "Stop"

# Auto-detect NOA_ROOT
if (-not $NoaRoot) {
    $NoaRoot = if ($env:NOA_ROOT) { $env:NOA_ROOT } else {
        Split-Path -Parent (Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $PSScriptRoot)))
    }
}

if (-not $OutputPath) {
    $OutputPath = Join-Path $NoaRoot "noa-env.ps1"
}

Write-Host "Generating NOA environment script..." -ForegroundColor Cyan

$envScript = @"
# NOA Environment Configuration
# Generated by scripts/bootstrap/generators/noa-env.ps1
# Date: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

# Core paths
`$env:NOA_ROOT = "$NoaRoot"
`$env:NOA_BIN = "`$env:NOA_ROOT\bin"
`$env:NOA_CONFIG = "`$env:NOA_ROOT\config"
`$env:NOA_SCRIPTS = "`$env:NOA_ROOT\scripts"
`$env:NOA_LOGS = "`$env:NOA_ROOT\logs"
`$env:NOA_CACHE = "`$env:NOA_ROOT\cache"

# Optional packages
`$env:NOA_OPT = "`$env:NOA_ROOT\opt"
`$env:NOA_REPOS = "`$env:NOA_ROOT\repos"
`$env:NOA_AI = "`$env:NOA_ROOT\ai"

# Kernel-related (NKAL)
`$env:NOA_SYS = "`$env:NOA_ROOT\sys"
`$env:NOA_NAMESPACE = "`$env:NOA_SYS\namespace"
`$env:NOA_CGROUP = "`$env:NOA_SYS\cgroup"
`$env:NOA_KERNEL = "`$env:NOA_SYS\kernel"

# Go environment
`$env:GOROOT = "`$env:NOA_OPT\go"
`$env:GOPATH = "`$env:NOA_OPT\go\workspace"
`$env:GOBIN = "`$env:NOA_OPT\go\workspace\bin"
`$env:GOCACHE = "`$env:NOA_CACHE\go"
`$env:GOMODCACHE = "`$env:NOA_OPT\go\pkg\mod"

# Rust environment
`$env:CARGO_HOME = "`$env:NOA_OPT\rust\cargo"
`$env:RUSTUP_HOME = "`$env:NOA_OPT\rust\rustup"

# Python environment
`$env:PIP_CACHE_DIR = "`$env:NOA_CACHE\pip"

# Node.js environment
`$env:npm_config_cache = "`$env:NOA_CACHE\npm"

# AI provider caches
`$env:OLLAMA_MODELS = "`$env:NOA_CACHE\ollama"
`$env:HF_HOME = "`$env:NOA_CACHE\huggingface"
`$env:LLAMA_CACHE = "`$env:NOA_CACHE\models"

# Add NOA directories to PATH
function Add-NoaPath {
    param([string]`$Dir)
    if (Test-Path `$Dir) {
        if (`$env:PATH -notlike "*`$Dir*") {
            `$env:PATH = "`$Dir;`$env:PATH"
        }
    }
}

Add-NoaPath `$env:NOA_BIN
Add-NoaPath `$env:NOA_SCRIPTS
Add-NoaPath (Join-Path `$env:GOROOT "bin")
Add-NoaPath `$env:GOBIN
Add-NoaPath (Join-Path `$env:CARGO_HOME "bin")

# Navigation aliases
function cda { Set-Location `$env:NOA_ROOT }
function cdr { Set-Location `$env:NOA_REPOS }
function cds { Set-Location `$env:NOA_SCRIPTS }
function cdc { Set-Location `$env:NOA_CONFIG }
function cdai { Set-Location `$env:NOA_AI }

Write-Host "NOA environment loaded: `$env:NOA_ROOT" -ForegroundColor Green
"@

$envScript | Set-Content -Path $OutputPath -Encoding UTF8
Write-Host "Generated: $OutputPath" -ForegroundColor Green

